apiVersion: nop.crossplane.io/v1alpha1
kind: NopResource
metadata:
  name: mr-2520
spec:
  forProvider:
    conditionAfter:
      - conditionStatus: "True"
        conditionType: Ready
        time: 1s
  providerConfigRef:
    name: default
