apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  generation: 1
  name: default
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  generation: 1
  name: default
spec:
  credentials:
    source: InjectedIdentity
